kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: log-topic
  labels:
    strimzi.io/cluster: kafka-example
  namespace: openshift-operators
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
