apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines-app
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/manifests/openshift-pipelines-operator/overlays/latest
    repoURL: https://github.com/joshuacanter/cluster-configs.git
    targetRevision: main
  spec:
    syncPolicy:
      automated: {}